### PR TITLE
Use gnmi generated getters to access the fields in a struct (#189)- m…

### PR DESCRIPTION
**Pull request by adibrastegarnia**
This pull request is for:

1- To address the issue #189 
2- To Address a TODO in the set function by consolidating lines into methods.

### CODE REVIEW

**Comment by stolsma** [comment]
Just for mijself, to learn something because I'm new to Golang: what is the gookg.lock file doing and why the (for me, but maybe its important) cosmetic change from arrays of lines to oneliners for filenames throughout the file?

**Comment by tomikazi** [comment]
It tracks changes in the external package dependencies. It is generated/updated by Go dep. 

Thomas

**Comment by stolsma** [comment]
Ah, thanks Thomas!

**Comment by adibrastegarnia** [comment]
> It would be good to add some documentation to the new methods as you create them. I'm not convinced this is productive breaking out in to functions that are only ever used once.

@SeanCondon 
Thanks for your comment. I am totally OK with adding comments to the new methods but it looks like we don't add comments to the functions that have not been exposed publicly and used for internal purposes inside a package. I didn't want to change the pattern if that is the case. Do you mean add comments in the body or somewhere else?

**Comment by SeanCondon** [comment]
I think we are free to add comments anywhere they help readability. The reason I thought comments might help here is it was not clear to me why this needed refactoring

**Pull request merged**
