### PR TITLE
Fixes so can run the model code-generation on macOS

### PR DESCRIPTION
**Pull request by k1eran**
Checked the sed part on macOS + Ubuntu + CentOS; I am not sure which development environment µonos team members normally use.

Deliberately split the ModelGenerator.sh changes into 4 small commits to explain each one.

### CODE REVIEW

**Comment by SeanCondon** [comment]
Kieran. Thanks for the update, looks great.

The rest of the team all run Mac, but I run Linux (rebel). I don't think anyone else on the team has tried this script.

I'm not sure about changing the name of the interface YANG file though - it won't work unless the `modified` is removed from the name, so adding YANG to the end won't do anything for it AFAIK.

**Comment by k1eran** [comment]
@SeanCondon  With the version in this pull request I get :
```
$ ./ModelGenerator.sh    Devicesim-1.0.0.env
YANGLIST openconfig-interfaces@2017-07-14.yang openconfig-openflow@2017-06-01.yang openconfig-platform@2016-12-22.yang openconfig-system@2017-07-06.yang

$ git status .
On branch fix/modelplugin-generate-on-macos
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Devicesim-1.0.0/devicesim_1_0_0/generated.go
	modified:   Devicesim-1.0.0/modelmain.go


```
But before hand e.g. when I revert like …
`$ mv yang/Devicesim-1.0.0/ietf-interfaces@2014-05-08.modified.yang yang/Devicesim-1.0.0/ietf-interfaces@2014-05-08.modified
`
I was getting :
```

$ ./ModelGenerator.sh    Devicesim-1.0.0.env
YANGLIST openconfig-interfaces@2017-07-14.yang openconfig-openflow@2017-06-01.yang openconfig-platform@2016-12-22.yang openconfig-system@2017-07-06.yang
F0116 15:17:39.579156   58068 generator.go:267] ERROR Generating Code: no such module: ietf-interfaces
exit status 1

```
When making the change I aimed to copy approach at 

`./yang/Stratum-1.0.0/ietf-interfaces@2014-05-08-modified.yang
`
WDYT ?

**Comment by SeanCondon** [comment]
I can't even get this working my self now - has YGOT changed?
```
scondon@Z420:~/go/src/github.com/onosproject/onos-config/modelplugin$ ./ModelGenerator.sh Devicesim-1.0.0.env 
YANGLIST openconfig-interfaces@2017-07-14.yang openconfig-openflow@2017-06-01.yang openconfig-platform@2016-12-22.yang openconfig-system@2017-07-06.yang
go: finding github.com/kylelemons/godebug/pretty latest
go: finding github.com/openconfig/ygot/genutil latest
build command-line-arguments: cannot load github.com/openconfig/ygot/genutil: cannot find module providing package github.com/openconfig/ygot/genutil
scondon@Z420:~/go/src/github.com/onosproject/onos-config/modelplugin$ 
```

If the solution works for you though then I'm OK with it - I was sure that it required the date to be after the `@`

**Comment by k1eran** [comment]
>has YGOT changed?

@SeanCondon  I also had problems with running the code-gen setup like :
`build command-line-arguments: cannot load github.com/openconfig/ygot/genutil: module github.com/openconfig/ygot@latest found (v0.6.0), but does not contain package github.com/openconfig/ygot/genutil`


Unfortunately the ygot official versions are old :

```
go list -m -versions github.com/openconfig/ygot
github.com/openconfig/ygot v0.5.0 v0.6.0

```


But I regarded that as separate from the macOS issues so have a separate pull request ready for that soon.


To get it to work I had to use a recent ygot (which we need for other reasons anyway), my next pull request has in the go.mod :

`	github.com/openconfig/ygot v0.6.1-0.20200103195725-e3c44fa43926
`

The steps I used were:
```
go get -u github.com/openconfig/ygot
cd $GOPATH/src/github.com/openconfig/ygot && go get -t -d ./...
go get github.com/openconfig/ygot@e3c44fa439262c24ff5d3dc62b662b10f49181c3 
```

**Pull request merged**
