### PR TITLE
fix ref to 1.0.x models in test

### PR DESCRIPTION
**Pull request by SeanCondon**

### CODE REVIEW

**Comment by SeanCondon** [comment]
retest this please

**Comment by SeanCondon** [comment]
retest this please

**Review by adibrastegarnia — APPROVED** [review]

**Review by ray-milkey — APPROVED** [review]

**Comment by ray-milkey** [comment]
retest this please

**Comment by SeanCondon** [comment]
retest this please

**Comment by SeanCondon** [comment]
thanks for reviewing Ray and Adib.
@kuujo - this is now giving an error on the atomix driver, but I think it's random and unrelated to the patch - just FYI

```
19:59:51 WARNING: DATA RACE
19:59:51 Read at 0x00c000368720 by goroutine 109:
19:59:51   runtime.mapaccess1_faststr()
19:59:51       /usr/lib/go/src/runtime/map_faststr.go:13 +0x0
19:59:51   github.com/atomix/atomix/runtime/pkg/network.(*localDriver).Listen()
19:59:51       /home/jenkins/workspace/verify_onos-config_make-test/onos-config/vendor/github.com/atomix/atomix/runtime/pkg/network/driver.go:63 +0x24f
19:59:51   github.com/atomix/atomix/runtime/pkg/network.(*grpcService).Start()
19:59:51       /home/jenkins/workspace/verify_onos-config_make-test/onos-config/vendor/github.com/atomix/atomix/runtime/pkg/network/service.go:38 +0x19a
19:59:51   github.com/atomix/go-sdk/pkg/test.(*Client).Connect()
19:59:51       /home/jenkins/workspace/verify_onos-config_make-test/onos-config/vendor/github.com/atomix/go-sdk/pkg/test/client.go:100 +0x7cf
19:59:51   github.com/atomix/go-sdk/pkg/primitive/map.(*mapBuilder[...]).Get()
19:59:51       /home/jenkins/workspace/verify_onos-config_make-test/onos-config/vendor/github.com/atomix/go-sdk/pkg/primitive/map/builder.go:41 +0x8e
19:59:51   github.com/atomix/go-sdk/pkg/primitive/map.(*mapBuilder[...]).Get()
19:59:51       <autogenerated>:1 +0x64
19:59:51   github.com/onosproject/onos-config/pkg/store/configuration.(*configurationStore).getTarget()
19:59:51       /home/jenkins/workspace/verify_onos-config_make-test/onos-config/pkg/store/configuration/configuration.go:576 +0x5e2
19:59:51   github.com/onosproject/onos-config/pkg/store/configuration.(*configurationStore).getApplied()
19:59:51       /home/jenkins/workspace/verify_onos-config_make-test/onos-config/pkg/store/configuration/configuration.go:521 +0x89
19:59:51   github.com/onosproject/onos-config/pkg/store/configuration.(*configurationStore).populate()
19:59:51       /home/jenkins/workspace/verify_onos-config_make-test/onos-config/pkg/store/configuration/configuration.go:492 +0x449
19:59:51   github.com/onosproject/onos-config/pkg/store/configuration.(*configurationStore).open.func1()
19:59:51       /home/jenkins/workspace/verify_onos-config_make-test/onos-config/pkg/store/configuration/configuration.go:146 +0x5e7
```

**Comment by SeanCondon** [comment]
retest this please

**Pull request merged**
