### PR TITLE
Add Proposal controller

### PR DESCRIPTION
**Pull request by kuujo**
This PR adds a new `Proposal` controller for managing the transactional changes/rollbacks associated with a specific target. The `Transaction` controller creates a `Proposal` for each target it affects, and `Proposal`s for each target are processed in transaction order. Both `Transaction`s and `Proposal`s progress through four phases:
* initialize - sets up the `Transaction` and `Proposal`s, e.g. linking neighboring `Proposal`s for navigation
* validate - validates the `Tansaction` and its `Proposal`s using RBAC and model plugins to determine whether the `Transaction` can be committed
* commit - commits the changes/rollbacks to associated target `Configuration`s
* apply - applies changes/rollbacks to targets via gNMI `Set`

The `Configuration` controller is no longer responsible for synchronizing changes as they're committed to the `Transaction` log. Instead, the `Configuration` controller is only responsible for recovering applied changes on ephemeral targets after a restart.

### CODE REVIEW

**Comment by kuujo** [comment]
retest this please

**Review by adibrastegarnia — APPROVED** [review]

**Comment by SeanCondon** [comment]
> This PR adds...

This is a great description - I hope this will be added to the documentation

**Comment by kuujo** [comment]
@SeanCondon I'm working on the documentation right now

**Comment by SeanCondon** [comment]
> 

:+1:

**Pull request merged**
