### PR TITLE
Adding the change context to configuration to get valid leaf-selectio…

### PR DESCRIPTION
**Pull request by frouzbeh**
…n values

### CODE REVIEW

**Comment by adibrastegarnia** [comment]
retest this please

**Comment by adibrastegarnia** [comment]
retest this please

**Comment by adibrastegarnia** [comment]
LGTM but lets wait for @SeanCondon  review

**Review by SeanCondon — COMMENTED** [review]
I think it probably is right, but I really could like to see `TestServer_LeafSelectionQuery_NoChange` duplicated with a ChangeContext
to prove it is right

**Review by SeanCondon — APPROVED** [review]
thanks for adding unit test - I don't know why it's failing - seems unrelated - proposal controller

**Comment by frouzbeh** [comment]
retest this please

**Comment by adibrastegarnia** [comment]
> thanks for adding unit test - I don't know why it's failing - seems unrelated - proposal controller

Recently I noticed unit tests fail for no reasons on Jenkins even they work fine locally. So perhaps times out or something like that on Jenkins.

**Pull request merged**
